### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kopach** [abatilo/release-info-action#2]
Hi. This projects looks promising for me, however I"m not sure how to use it. Could you, explain, please, which variables will be available once I use this project? And also, whether there is any need in proper setup before usage of release-info-action. Thanks

**Comment by abatilo** [comment]
Hi @kopach !

Thanks for the feedback. I've committed some improvements to the README for this project that hopefully answers your questions and gives you what you need. It includes an actual working example  that you can find [here](https://github.com/abatilo/release-info-action/blob/5ec0b35d235da834b75339bd96390023f3cebe33/.github/workflows/example.yml).

Please let me know if there's anything else we can improve on!
