### ISSUE TITLE
Failure somewhere returns "null" instead of failure

### ISSUE THREAD

**Issue by mortenlj** [abatilo/release-info-action#23]
We recently had a case where release-info-action returned "null" for all its fields.
https://github.com/nais/device/actions/runs/4687068419/jobs/8305897271#step:4:29

Probably there was an error in curl or elsewhere, but instead of failing the action, "null" is returned instead.

Would it be better to fail in these cases?

**Comment by abatilo** [comment]
That sounds great @mortenlj. Would you like to contribute a fix?

**Comment by mortenlj** [comment]
I did a quick PR. I think setting those flags for bash should fix it.
