### ISSUE TITLE
Updating to v1.2.0 doesn't fix curl install issue

### ISSUE THREAD

**Issue by jamescooke** [abatilo/release-info-action#6]
This might be a GitHub Actions problem - but please let me know if you know of any reason that this might be happening...

I've updated to use v1.2.0 here: https://github.com/jamescooke/openapi-validator-docker/commit/96925ddec04a7725fc19531f66d683b98296231f

However, although the Action build says it's using v1.2.0, it still tries to install `curl=7.66.0-r0` into alpine 3.10.2 and fails, even though v1.2.0 here has `curl` on alpine 3.12.0 - you can see that here: https://github.com/jamescooke/openapi-validator-docker/runs/1122151352

Is there something I'm missing that's required to update the Action, some cache to pop or something that release-info-action needs?

I have run the Dockerfile of v1.2.0 locally and it can build an image :+1:

**Comment by jamescooke** [comment]
Found the problem - sorry for any confusion. v1.2.0 does *not* have alpine 3.12.0, it's still on 3.10.2.

I also wrongly assumed that `v1.2.0==master`, but that's not correct: https://github.com/abatilo/release-info-action/compare/v1.2.0...master

I'll see if using current master fixes the issue for me.

**Comment by jamescooke** [comment]
Run fixed here using latest commit on master (https://github.com/abatilo/release-info-action/commit/0b80b860c5c5aa1072ab6b28fa7d1c80b4ba3c78) : https://github.com/jamescooke/openapi-validator-docker/runs/1123066723?check_suite_focus=true

IMO it would be good to release v1.2.1 and point it at https://github.com/abatilo/release-info-action/commit/0b80b860c5c5aa1072ab6b28fa7d1c80b4ba3c78 in case others have this issue.

**Comment by abatilo** [comment]
Thanks for investigating on my behalf @jamescooke.

Let me try to get something out asap.

**Comment by jamescooke** [comment]
Thanks @abatilo :+1:
